run-wine-5nn:
	python main.py data/wine.csv 5

run-validate-4nn:
	python main.py data/lattice_40x40.csv 4 validate

run-random-10nn:
	python main.py data/lattice_40x40_random.csv 10

run-yeast-28nn:
	python main.py data/yeast_times100.csv 28

test:
	python tester.py
